/**
 * Created by gxy on 2017/6/5.
 */
/****************************************************************
 389. Find the Difference
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
****************************************************************/
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
  var map={},res='';
  for(var i=0;i<s.length;i++) map[s[i]]=map[s[i]]==undefined?1:map[s[i]]+1;
  for(i=0;i<t.length;i++) {
    if(!map[t[i]]) {
      res=t[i];
      break;
    } else map[t[i]]--;
  }
  return res;
};

//test
var  s = "a",t = "aa";
var algo = "algo";
console.time(algo);
var res = findTheDifference(s,t);
console.timeEnd(algo);
console.log("res:",res);